---
title: "margin and win% for HT and FT"
output: html_document
---

GOAL:
Extract Half Time and Full Time scores

Links can only have win or loss matches!

```{r}
#store the links to all pages required

home.england <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=1;template=results;trophy=17;type=team;view=results"

away.england <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=1;template=results;type=team;view=results"

home.france <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=9;template=results;trophy=17;type=team;view=results"
  
away.france <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=9;template=results;type=team;view=results"

home.ireland <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=3;template=results;trophy=17;type=team;view=results"

away.ireland <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=3;template=results;type=team;view=results"

home.italy <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=20;template=results;trophy=17;type=team;view=results"

away.italy <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=20;template=results;type=team;view=results"

home.scotland <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=2;template=results;trophy=17;type=team;view=results"

away.scotland <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=2;template=results;type=team;view=results"

home.wales <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=4;template=results;trophy=17;type=team;view=results"

away.wales <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;filter=advanced;opposition=1;opposition=10;opposition=2;opposition=20;opposition=3;opposition=4;opposition=5;opposition=6;opposition=8;opposition=9;orderby=date;result=1;result=2;size=200;spanmax1=31+Dec+2015;spanmin1=1+Jan+2003;spanval1=span;team=4;template=results;type=team;view=results"
```

```{r}
#extract the 40 cells of data
library(rvest)

home.england.html.vector <- readLines(home.england)

home.england.html.lines <- regmatches(home.england.html.vector, regexpr("<td>[[:digit:]]{1,3}</td>", home.england.html.vector))

home.england <- substr(home.england.html.lines, 5, nchar(home.england.html.lines)-5)

home.england.matrix <- matrix(as.integer(home.england), ncol = 4, byrow = TRUE)
home.england.matrix
```

These are the 40 cells we are interested in.

The pattern is:

FTFor, FTAgainst, HTFor, HTAgainst

```{r}
#The logic above as a function

extract.score.cells.from.webpage <- function(link){
  html.vector <- readLines(link)
  html.lines <- regmatches(html.vector, regexpr("<td>[[:digit:]]{1,3}</td>", html.vector))
  html.lines.trimmed <- substr(html.lines, 5, nchar(html.lines)-5)
  matrix <- matrix(as.integer(html.lines.trimmed), ncol = 4, byrow = TRUE)
  return(matrix)
}

#Missing data for Australia vs France 2014

extract.score.cells.from.webpage.special <- function(link){
  html.vector <- readLines(link)
  html.lines <- regmatches(html.vector, regexpr("<td>[[:digit:]]{1,3}</td>", html.vector))
  index <- length(html.lines) - 55
  html.lines.trimmed <- substr(html.lines, 5, nchar(html.lines)-5)[-c(index,index+1)]
  matrix <- matrix(as.integer(html.lines.trimmed), ncol = 4, byrow = TRUE)
  return(matrix)
}
```

```{r}
write.csv(home.england.matrix, "./6nationsHomeAdvantages/home.england.matrix.csv")

#Run the function for the other 11 links
#Then save it as a csv to be safe

away.england.matrix <- extract.score.cells.from.webpage(away.england)
write.csv(away.england.matrix, "./6nationsHomeAdvantages/away.england.matrix.csv")

away.france.matrix <- extract.score.cells.from.webpage.special(away.france)
write.csv(away.france.matrix, "./6nationsHomeAdvantages/away.france.matrix.csv")

away.ireland.matrix <- extract.score.cells.from.webpage(away.ireland)
write.csv(away.ireland.matrix, "./6nationsHomeAdvantages/away.ireland.matrix.csv")

away.italy.matrix <- extract.score.cells.from.webpage(away.italy)
write.csv(away.italy.matrix, "./6nationsHomeAdvantages/away.italy.matrix.csv")

away.scotland.matrix <- extract.score.cells.from.webpage(away.scotland)
write.csv(away.scotland.matrix, "./6nationsHomeAdvantages/away.scotland.matrix.csv")

home.france.matrix <- extract.score.cells.from.webpage(home.france)
write.csv(home.france.matrix, "./6nationsHomeAdvantages/home.france.matrix.csv")

home.italy.matrix <- extract.score.cells.from.webpage(home.italy)
write.csv(home.italy.matrix, "./6nationsHomeAdvantages/home.italy.matrix.csv")

home.scotland.matrix <- extract.score.cells.from.webpage(home.scotland)
write.csv(home.scotland.matrix, "./6nationsHomeAdvantages/home.scotland.matrix.csv")

home.wales.matrix <- extract.score.cells.from.webpage(home.wales)
write.csv(home.wales.matrix, "./6nationsHomeAdvantages/home.wales.matrix.csv")

away.wales.matrix <- extract.score.cells.from.webpage(away.wales)
write.csv(away.wales.matrix, "./6nationsHomeAdvantages/away.wales.matrix.csv")

home.ireland.matrix <- extract.score.cells.from.webpage(home.ireland)
write.csv(home.ireland.matrix, "./6nationsHomeAdvantages/home.ireland.matrix.csv")
```